[build-system]
requires = [
    "setuptools",
    "wheel",
]

[tool.black]
skip-string-normalization = true

[tool.isort]
profile = "black"
# Python 2 stdlib
extra_standard_library = ["urlparse", "HTMLParser", "urllib2"]
